---
# Chart: test_chart
# Source: /path/to/ankh.yaml
default-values:
  default_key: default_value
values:
  production:
    log_level: 3
  dev:
    log_level: 10
resource-profiles:
  natural:
    cpu: 0.3
  constrained:
    cpu: 0.1
releases:
  production:
    host: test.external.com
  staging:
    host: test.internal.net
---
# Source: /tmp/ankh/ankh-values.yaml
production:
  port: 80
dev:
  port: 8080
---
# Source: /tmp/ankh/ankh-resource-profiles.yaml
constrained:
  replicas: 1
natural:
  replicas: 2
---
# Source: /tmp/ankh/ankh-releases.yaml
production:
  host: test.external.com
staging:
  host: test.internal.net
---
# Source: /tmp/ankh/values.yaml
host: localhost
port: 8080
name: test-app
