---
# Chart: test_chart
# Source: /path/to/ankh.yaml
default-values:
  default_key: default_value
values:
  log_level: 10
resource-profiles:
  cpu: 0.1
releases:
  host: test.internal.net
---
# Source: /tmp/ankh/ankh-values.yaml
port: 8080
---
# Source: /tmp/ankh/ankh-resource-profiles.yaml
replicas: 1
---
# Source: /tmp/ankh/ankh-releases.yaml
host: test.internal.net
---
# Source: /tmp/ankh/values.yaml
host: localhost
port: 8080
name: test-app
